#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Assessment5/Assessment5.csproj", "Assessment5/"]
RUN dotnet restore "Assessment5/Assessment5.csproj"
COPY . .
WORKDIR "/src/Assessment5"
RUN dotnet build "Assessment5.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Assessment5.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Assessment5.dll"]